# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20210610-JigarPatel-NYCSchools' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for 20210610-JigarPatel-NYCSchools
#  pod "CellAnimator"
  pod "ViewAnimator"
  pod "NVActivityIndicatorView"

  target '20210610-JigarPatel-NYCSchoolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20210610-JigarPatel-NYCSchoolsUITests' do
    # Pods for testing
  end

end
